name: XUMM SDK CI (node)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Fix Windows Git autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npm run lint
    - run: npm run build
    - run: npm run test
      env:
        XUMM_APIKEY: aaaaaaaa-cccc-eeee-1111-333333333333
        XUMM_APISECRET: bbbbbbbb-dddd-ffff-2222-444444444444

  deno:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        deno-version: [v1.x, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Fix Windows Git autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v2
    - name: Setup Deno ${{ matrix.deno-version }}
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}
    - run: deno lint --unstable mod.ts deno/*.ts deno/*/*
    - run: deno test --allow-read=.env,.env.defaults --allow-env=DEBUG,XUMM_API* mod.ts
      env:
        XUMM_APIKEY: aaaaaaaa-cccc-eeee-1111-333333333333
        XUMM_APISECRET: bbbbbbbb-dddd-ffff-2222-444444444444